@startuml

class Route {
    --
    match:Object
}

class MapPage {
    sprayingId:number
    sectionId:number
    --
    spraying:Spraying
    isSprayingLoading:bool
}

class Sidebar {
    spraying:Spraying
    --
}

class Map {
    spraying:Spraying
    sectionId:number
    --
    selectedSectionId:number
}

class SprayingSelect {
    #history:Object
    --
    sprayingId:number
    --
    shortSprayingDescriptionList:ShortSprayingDescription[]
    isShortSprayingDescriptionListLoading:bool
}

class SprayingDescription {
    description:SprayingDescription
}

class SprayingSummary {
    summary:SprayingSummary
    --
    areSectorsVisible:bool
}

class Details {
    summary:SprayingSummary
    --
}

Route -- MapPage

MapPage -- Sidebar
MapPage -- Map

Sidebar -- SprayingSelect
Sidebar -- SprayingDescription
Sidebar -- SprayingSummary
Sidebar -- Details

@enduml
