@startuml

class Route {
    --
    match:Object
}

class TablePage {
    sprayingId:number
    --
    spraying:Spraying
    isSprayingLoading:bool
    --
    -spraying:Spraying
}

class Control {
    --
    weed:bool
    chemical1:bool
    chemical2:bool
    chemical3:bool
    chemical4:bool
}

class Info {
    description:SprayingDescription
}

class SprayingTable {
    -spraying:Spraying
    --
    areWeedSectorsVisible:bool
    chemicalSectorVisibility:Array
}

Route -- TablePage
TablePage -- Control
TablePage -- Info
Control -- SprayingTable

@enduml
